name: CI Build

on: pull_request

jobs:
  build:
    name: Check Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone X']
    steps:
      - uses: actions/checkout@master
      - name: Build 
        run: |
         carthage update --platform ios
         xcodebuild clean build -project kintone-ios-sdk.xcodeproj -scheme kintone-ios-sdk -sdk iphonesimulator -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with: 
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: buid/kintone-ios-sdk-gbovytkbfubiwxgrkdawjgcphkme/Build/Products/Debug-iphonesimulator/kintone_ios_sdk.framework
          asset_name: kintone_ios_sdk.framework
          tag: ${{ github.ref }}
          overwrite: true
